oro_tag_assign_unassign:
    label: Tag assign/unassign
    type: action
    group_name: ""
    bindings: ~

oro_tag_unassign_global:
    label: Unassign all tags from entities
    type: action
    group_name: ""
    bindings: ~

oro_tag_view_tag_cloud:
    label:  View tag cloud
    type: action
    group_name: ""
    bindings: ~
