oro_tag_assign:
    name: Tag assign
    description: User can assign tags for entities and unassign only which were assigned by this user
    parent: oro_tag

oro_tag_unassign:
    name: Tag unassign
    description: User can unassign all tags from entities
    parent: oro_tag_assign
