oro_tag_assign_unassign:
    name: Tag assign/unassign
    description: User can assign tags for entities and unassign only which were assigned by this user
    parent: oro_tag

oro_tag_unassign_global:
    name: Tag unassign global
    description: User can unassign all tags from entities
    parent: oro_tag
