parameters:
    oro_tag.datagrid_manager.class:        Oro\Bundle\TagBundle\Datagrid\TagDatagridManager

services:
    oro_tag.datagrid_manager:
        class: %oro_tag.datagrid_manager.class%
        tags:
            - name: oro_grid.datagrid.manager
              datagrid_name: accounts
              entity_name: %oro_tag.tag.entity.class%
              entity_hint: tags
              route_name: oro_tag_index
