datagrid:
    tag-grid:
        source:
            acl_resource: oro_tag_view
            type: orm
            query:
                select:
                    - t.id
                    - t.name
                    - COUNT(t.id) as usage
                from:
                    - { table: OroTagBundle:Tag, alias: t }
                join:
                    left:
                        tagging:
                            join: t.tagging
                            alias: tt
                groupBy: t.id

        columns:
            name:
                label: Tag
                type: field
                frontend_type: string
            usage:
                label: Usage Count
                type: field
                frontend_type: integer

        properties:
            update_link:
                type: url
                route: oro_tag_update
                params:
                    - id
            search_link:
                type: url
                route: oro_tag_search
                params:
                    - id
            delete_link:
                type: url
                route: oro_api_delete_tag
                params:
                    - id
        sorters:
            columns:
                name:
                    data_name: t.name
                usage:
                    data_name: usage
            default:
                label: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC

        filters:
            columns:
                name:
                    type: string
                    data_name: t.name
                usage:
                    type: string
                    data_name: usage

    tag-results-grid:
        source:
            acl_resource: oro_tag_view
            type: orm
            query:
                select:
                    - tt
                    - t
                from:
                    - { table: OroTagBundle:Tagging, alias: tt }
                join:
                    left:
                        tagging:
                            join: tt.tag
                            alias: t
                groupBy: tt.entityName, tt.recordId
                where:
                    and:
                        - tt.tag = :tag
        columns:
            entity:
                label: Item
                type: search-result
                template: OroTagBundle::Search\result.html.twig
                frontend_type: string

        properties: ~
        sorters: ~
        filters: ~
