oro_entity_config:
    tag:
        entity:
            items:
                # indicates whether the entity can have tags or not
                enabled: # boolean
                    options:
                        require_schema_update: false
                        priority:           250
                        default_value:      false
                    form:
                        # @todo: Should be refactored in CRM-4597
                        # Need specify own choice type, disable editing for Taggable entities
                        type:               oro_entity_extend_association_choice
                        options:
                            block:          other
                            required:       true
                            label:          oro.tag.tagging.entity_label
