oro_entity_config:
    tag:
        entity:
            items:
                # indicates whether the entity can have tags or not
                enabled: # boolean
                    options:
                        require_schema_update: false
                        priority:              250
                        default_value:         false
                    form:
                        type:               oro_tag_config_choice
                        options:
                            block:          other
                            required:       true
                            label:          oro.tag.tagging.entity_label
