oro_menu_config:
    items:
        oro_tag_list:
            label: 'Tags'
            route: 'oro_tag_index'
            extras:
                routes: ['oro_tag_*']
    tree:
        application_menu:
            children:
                system_tab:
                    children:
                        oro_tag_list: ~

oro_titles:
    oro_tag_index:  Tags
    oro_tag_update: Edit "%%tag.name%%" tag
    oro_tag_create: Create tag
    oro_tag_search: Records tagged as "%%tag.name%%"
