Oro\Bundle\TagBundle\Entity\Tag:
    alias:                          oro_tag
    title_fields:                   [name]
    search_template:                OroTagBundle:Search:result.html.twig
    fields:
        -
            name:                   name
            target_type:            text
            target_fields:          [name]
