Oro\Bundle\TagBundle\Entity\Tag:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        name:
            - NotBlank:     ~
            - Length:
                min:        1
                max:        255
